// 内置死活题（程序化生成并经引擎验证）。answers 为所有可达成目标的正解点。
window.TSUMEGO_PROBLEMS = [
  { id:"t001", title:"做活·入门", difficulty:"入门", type:"做活", tags:["眼位","做眼"],
    size:9, setup:"AB[aa][ba][ca][da][ea][ab][eb][ac][bc][cc][dc][ec]", solver:1, target:[1,1], goal:"live", answers:[[2,1]] },
  { id:"t002", title:"做活·初级", difficulty:"初级", type:"做活", tags:["眼位","做眼"],
    size:9, setup:"AB[aa][ba][ca][da][ea][ab][eb][ac][bc][dc][ec][bd][cd][dd]", solver:1, target:[1,1], goal:"live", answers:[[2,1]] },
  { id:"t003", title:"做活·中级", difficulty:"中级", type:"做活", tags:["眼位","做眼"],
    size:9, setup:"AB[aa][ba][ca][da][ea][fa][ab][fb][ac][bc][dc][ec][fc][bd][cd][dd]", solver:1, target:[1,1], goal:"live", answers:[[2,1]] },
  { id:"t004", title:"做活·入门", difficulty:"入门", type:"做活", tags:["眼位","做眼"],
    size:9, setup:"AB[ab][bb][cb][db][eb][ac][ec][ad][bd][cd][dd][ed]", solver:1, target:[1,2], goal:"live", answers:[[2,2]] },
  { id:"t005", title:"做活·初级", difficulty:"初级", type:"做活", tags:["眼位","做眼"],
    size:9, setup:"AB[ab][bb][cb][db][eb][ac][ec][ad][bd][dd][ed][be][ce][de]", solver:1, target:[1,2], goal:"live", answers:[[2,2]] },
  { id:"t006", title:"做活·中级", difficulty:"中级", type:"做活", tags:["眼位","做眼"],
    size:9, setup:"AB[ab][bb][cb][db][eb][fb][ac][fc][ad][bd][dd][ed][fd][be][ce][de]", solver:1, target:[1,2], goal:"live", answers:[[2,2]] },
  { id:"t007", title:"做活·入门", difficulty:"入门", type:"做活", tags:["眼位","做眼"],
    size:9, setup:"AB[ac][bc][cc][dc][ec][ad][ed][ae][be][ce][de][ee]", solver:1, target:[1,3], goal:"live", answers:[[2,3]] },
  { id:"t008", title:"做活·初级", difficulty:"初级", type:"做活", tags:["眼位","做眼"],
    size:9, setup:"AB[ac][bc][cc][dc][ec][ad][ed][ae][be][de][ee][bf][cf][df]", solver:1, target:[1,3], goal:"live", answers:[[2,3]] },
  { id:"t009", title:"做活·中级", difficulty:"中级", type:"做活", tags:["眼位","做眼"],
    size:9, setup:"AB[ac][bc][cc][dc][ec][fc][ad][fd][ae][be][de][ee][fe][bf][cf][df]", solver:1, target:[1,3], goal:"live", answers:[[2,3]] },
  { id:"t010", title:"做活·入门", difficulty:"入门", type:"做活", tags:["眼位","做眼"],
    size:9, setup:"AB[ad][bd][cd][dd][ed][ae][ee][af][bf][cf][df][ef]", solver:1, target:[1,4], goal:"live", answers:[[2,4]] },
  { id:"t011", title:"做活·初级", difficulty:"初级", type:"做活", tags:["眼位","做眼"],
    size:9, setup:"AB[ad][bd][cd][dd][ed][ae][ee][af][bf][df][ef][bg][cg][dg]", solver:1, target:[1,4], goal:"live", answers:[[2,4]] },
  { id:"t012", title:"做活·中级", difficulty:"中级", type:"做活", tags:["眼位","做眼"],
    size:9, setup:"AB[ba][ca][da][ea][fa][ga][bb][gb][bc][cc][ec][fc][gc][cd][dd][ed]", solver:1, target:[2,1], goal:"live", answers:[[3,1]] },
  { id:"t013", title:"做活·入门", difficulty:"入门", type:"做活", tags:["眼位","做眼"],
    size:9, setup:"AB[ba][ca][da][ea][fa][bb][fb][bc][cc][dc][ec][fc]", solver:1, target:[2,1], goal:"live", answers:[[3,1]] },
  { id:"t014", title:"做活·初级", difficulty:"初级", type:"做活", tags:["眼位","做眼"],
    size:9, setup:"AB[ba][ca][da][ea][fa][bb][fb][bc][cc][ec][fc][cd][dd][ed]", solver:1, target:[2,1], goal:"live", answers:[[3,1]] },
  { id:"t015", title:"做活·中级", difficulty:"中级", type:"做活", tags:["眼位","做眼"],
    size:9, setup:"AB[bb][cb][db][eb][fb][gb][bc][gc][bd][cd][ed][fd][gd][ce][de][ee]", solver:1, target:[2,2], goal:"live", answers:[[3,2]] },
  { id:"t016", title:"做活·入门", difficulty:"入门", type:"做活", tags:["眼位","做眼"],
    size:9, setup:"AB[bb][cb][db][eb][fb][bc][fc][bd][cd][dd][ed][fd]", solver:1, target:[2,2], goal:"live", answers:[[3,2]] },
  { id:"t017", title:"做活·初级", difficulty:"初级", type:"做活", tags:["眼位","做眼"],
    size:9, setup:"AB[bb][cb][db][eb][fb][bc][fc][bd][cd][ed][fd][ce][de][ee]", solver:1, target:[2,2], goal:"live", answers:[[3,2]] },
  { id:"t018", title:"做活·中级", difficulty:"中级", type:"做活", tags:["眼位","做眼"],
    size:9, setup:"AB[bc][cc][dc][ec][fc][gc][bd][gd][be][ce][ee][fe][ge][cf][df][ef]", solver:1, target:[2,3], goal:"live", answers:[[3,3]] },
  { id:"t019", title:"做活·入门", difficulty:"入门", type:"做活", tags:["眼位","做眼"],
    size:9, setup:"AB[bc][cc][dc][ec][fc][bd][fd][be][ce][de][ee][fe]", solver:1, target:[2,3], goal:"live", answers:[[3,3]] },
  { id:"t020", title:"做活·初级", difficulty:"初级", type:"做活", tags:["眼位","做眼"],
    size:9, setup:"AB[bc][cc][dc][ec][fc][bd][fd][be][ce][ee][fe][cf][df][ef]", solver:1, target:[2,3], goal:"live", answers:[[3,3]] },
  { id:"t021", title:"做活·中级", difficulty:"中级", type:"做活", tags:["眼位","做眼"],
    size:9, setup:"AB[ca][da][ea][fa][ga][ha][cb][hb][cc][dc][fc][gc][hc][dd][ed][fd]", solver:1, target:[3,1], goal:"live", answers:[[4,1]] },
  { id:"t022", title:"做活·入门", difficulty:"入门", type:"做活", tags:["眼位","做眼"],
    size:9, setup:"AB[bd][cd][dd][ed][fd][be][fe][bf][cf][df][ef][ff]", solver:1, target:[2,4], goal:"live", answers:[[3,4]] },
  { id:"t023", title:"做活·初级", difficulty:"初级", type:"做活", tags:["眼位","做眼"],
    size:9, setup:"AB[bd][cd][dd][ed][fd][be][fe][bf][cf][ef][ff][cg][dg][eg]", solver:1, target:[2,4], goal:"live", answers:[[3,4]] },
  { id:"t024", title:"做活·中级", difficulty:"中级", type:"做活", tags:["眼位","做眼"],
    size:9, setup:"AB[cb][db][eb][fb][gb][hb][cc][hc][cd][dd][fd][gd][hd][de][ee][fe]", solver:1, target:[3,2], goal:"live", answers:[[4,2]] },
  { id:"t025", title:"做活·入门", difficulty:"入门", type:"做活", tags:["眼位","做眼"],
    size:9, setup:"AB[ca][da][ea][fa][ga][cb][gb][cc][dc][ec][fc][gc]", solver:1, target:[3,1], goal:"live", answers:[[4,1]] },
  { id:"t026", title:"杀棋·入门", difficulty:"入门", type:"杀棋", tags:["眼位","杀棋"],
    size:9, setup:"AW[aa][ba][ca][da][ea][ab][eb][ac][bc][cc][dc][ec]", solver:1, target:[1,1], goal:"kill", answers:[[2,1]] },
  { id:"t027", title:"杀棋·初级", difficulty:"初级", type:"杀棋", tags:["眼位","杀棋"],
    size:9, setup:"AW[aa][ba][ca][da][ea][ab][eb][ac][bc][dc][ec][bd][cd][dd]", solver:1, target:[1,1], goal:"kill", answers:[[2,1]] },
  { id:"t028", title:"杀棋·中级", difficulty:"中级", type:"杀棋", tags:["眼位","杀棋"],
    size:9, setup:"AW[aa][ba][ca][da][ea][fa][ab][fb][ac][bc][dc][ec][fc][bd][cd][dd]", solver:1, target:[1,1], goal:"kill", answers:[[2,1]] },
  { id:"t029", title:"杀棋·入门", difficulty:"入门", type:"杀棋", tags:["眼位","杀棋"],
    size:9, setup:"AW[ab][bb][cb][db][eb][ac][ec][ad][bd][cd][dd][ed]", solver:1, target:[1,2], goal:"kill", answers:[[2,2]] },
  { id:"t030", title:"杀棋·初级", difficulty:"初级", type:"杀棋", tags:["眼位","杀棋"],
    size:9, setup:"AW[ab][bb][cb][db][eb][ac][ec][ad][bd][dd][ed][be][ce][de]", solver:1, target:[1,2], goal:"kill", answers:[[2,2]] },
  { id:"t031", title:"杀棋·中级", difficulty:"中级", type:"杀棋", tags:["眼位","杀棋"],
    size:9, setup:"AW[ab][bb][cb][db][eb][fb][ac][fc][ad][bd][dd][ed][fd][be][ce][de]", solver:1, target:[1,2], goal:"kill", answers:[[2,2]] },
  { id:"t032", title:"杀棋·入门", difficulty:"入门", type:"杀棋", tags:["眼位","杀棋"],
    size:9, setup:"AW[ac][bc][cc][dc][ec][ad][ed][ae][be][ce][de][ee]", solver:1, target:[1,3], goal:"kill", answers:[[2,3]] },
  { id:"t033", title:"杀棋·初级", difficulty:"初级", type:"杀棋", tags:["眼位","杀棋"],
    size:9, setup:"AW[ac][bc][cc][dc][ec][ad][ed][ae][be][de][ee][bf][cf][df]", solver:1, target:[1,3], goal:"kill", answers:[[2,3]] },
  { id:"t034", title:"杀棋·中级", difficulty:"中级", type:"杀棋", tags:["眼位","杀棋"],
    size:9, setup:"AW[ac][bc][cc][dc][ec][fc][ad][fd][ae][be][de][ee][fe][bf][cf][df]", solver:1, target:[1,3], goal:"kill", answers:[[2,3]] },
  { id:"t035", title:"杀棋·入门", difficulty:"入门", type:"杀棋", tags:["眼位","杀棋"],
    size:9, setup:"AW[ad][bd][cd][dd][ed][ae][ee][af][bf][cf][df][ef]", solver:1, target:[1,4], goal:"kill", answers:[[2,4]] },
  { id:"t036", title:"杀棋·初级", difficulty:"初级", type:"杀棋", tags:["眼位","杀棋"],
    size:9, setup:"AW[ad][bd][cd][dd][ed][ae][ee][af][bf][df][ef][bg][cg][dg]", solver:1, target:[1,4], goal:"kill", answers:[[2,4]] },
  { id:"t037", title:"杀棋·中级", difficulty:"中级", type:"杀棋", tags:["眼位","杀棋"],
    size:9, setup:"AW[ba][ca][da][ea][fa][ga][bb][gb][bc][cc][ec][fc][gc][cd][dd][ed]", solver:1, target:[2,1], goal:"kill", answers:[[3,1]] },
  { id:"t038", title:"杀棋·入门", difficulty:"入门", type:"杀棋", tags:["眼位","杀棋"],
    size:9, setup:"AW[ba][ca][da][ea][fa][bb][fb][bc][cc][dc][ec][fc]", solver:1, target:[2,1], goal:"kill", answers:[[3,1]] },
  { id:"t039", title:"杀棋·初级", difficulty:"初级", type:"杀棋", tags:["眼位","杀棋"],
    size:9, setup:"AW[ba][ca][da][ea][fa][bb][fb][bc][cc][ec][fc][cd][dd][ed]", solver:1, target:[2,1], goal:"kill", answers:[[3,1]] },
  { id:"t040", title:"杀棋·中级", difficulty:"中级", type:"杀棋", tags:["眼位","杀棋"],
    size:9, setup:"AW[bb][cb][db][eb][fb][gb][bc][gc][bd][cd][ed][fd][gd][ce][de][ee]", solver:1, target:[2,2], goal:"kill", answers:[[3,2]] },
  { id:"t041", title:"杀棋·入门", difficulty:"入门", type:"杀棋", tags:["眼位","杀棋"],
    size:9, setup:"AW[bb][cb][db][eb][fb][bc][fc][bd][cd][dd][ed][fd]", solver:1, target:[2,2], goal:"kill", answers:[[3,2]] },
  { id:"t042", title:"杀棋·初级", difficulty:"初级", type:"杀棋", tags:["眼位","杀棋"],
    size:9, setup:"AW[bb][cb][db][eb][fb][bc][fc][bd][cd][ed][fd][ce][de][ee]", solver:1, target:[2,2], goal:"kill", answers:[[3,2]] },
  { id:"t043", title:"杀棋·中级", difficulty:"中级", type:"杀棋", tags:["眼位","杀棋"],
    size:9, setup:"AW[bc][cc][dc][ec][fc][gc][bd][gd][be][ce][ee][fe][ge][cf][df][ef]", solver:1, target:[2,3], goal:"kill", answers:[[3,3]] },
  { id:"t044", title:"杀棋·入门", difficulty:"入门", type:"杀棋", tags:["眼位","杀棋"],
    size:9, setup:"AW[bc][cc][dc][ec][fc][bd][fd][be][ce][de][ee][fe]", solver:1, target:[2,3], goal:"kill", answers:[[3,3]] },
  { id:"t045", title:"杀棋·初级", difficulty:"初级", type:"杀棋", tags:["眼位","杀棋"],
    size:9, setup:"AW[bc][cc][dc][ec][fc][bd][fd][be][ce][ee][fe][cf][df][ef]", solver:1, target:[2,3], goal:"kill", answers:[[3,3]] },
  { id:"t046", title:"杀棋·中级", difficulty:"中级", type:"杀棋", tags:["眼位","杀棋"],
    size:9, setup:"AW[ca][da][ea][fa][ga][ha][cb][hb][cc][dc][fc][gc][hc][dd][ed][fd]", solver:1, target:[3,1], goal:"kill", answers:[[4,1]] },
  { id:"t047", title:"杀棋·入门", difficulty:"入门", type:"杀棋", tags:["眼位","杀棋"],
    size:9, setup:"AW[bd][cd][dd][ed][fd][be][fe][bf][cf][df][ef][ff]", solver:1, target:[2,4], goal:"kill", answers:[[3,4]] },
  { id:"t048", title:"杀棋·初级", difficulty:"初级", type:"杀棋", tags:["眼位","杀棋"],
    size:9, setup:"AW[bd][cd][dd][ed][fd][be][fe][bf][cf][ef][ff][cg][dg][eg]", solver:1, target:[2,4], goal:"kill", answers:[[3,4]] },
  { id:"t049", title:"杀棋·中级", difficulty:"中级", type:"杀棋", tags:["眼位","杀棋"],
    size:9, setup:"AW[cb][db][eb][fb][gb][hb][cc][hc][cd][dd][fd][gd][hd][de][ee][fe]", solver:1, target:[3,2], goal:"kill", answers:[[4,2]] },
  { id:"t050", title:"杀棋·入门", difficulty:"入门", type:"杀棋", tags:["眼位","杀棋"],
    size:9, setup:"AW[ca][da][ea][fa][ga][cb][gb][cc][dc][ec][fc][gc]", solver:1, target:[3,1], goal:"kill", answers:[[4,1]] },
];
